services:
  - type: web
    name: ensemble
    runtime: python
    buildCommand: chmod +x bin/render-build.sh && ./bin/render-build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 4 "app:create_app()"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
